name: macos build

on: workflow_dispatch

# env:
#   RUSTFLAGS: -Dwarnings # Turn warnings into errors
#   RUST_CI: true

jobs:
  macos:
    runs-on: macos-latest
    env:
      INSTA_USER: ${{ secrets.INSTA_USER }}
      INSTA_PASS: ${{ secrets.INSTA_PASS }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: echo "insta_user = '$INSTA_USER'" >> .env
      - run: echo "insta_pass = '$INSTA_PASS'" >> .env
      - run: cat .env
      - run: cargo build --release
      - run: cargo build --release --target aarch64-apple-darwin
      - run: cargo build --release --target x86_64-apple-darwin
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: |
            target/release/instagram-comments-scraper
            target/**/release/instagram-comments-scraper
